# Cleanup workflow for managing Docker registry storage
name: Delete Container Versions

on:
  schedule:
    # Run weekly on Sundays at 02:00 UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      package_type:
        required: true
        type: string
      min_versions_to_keep:
        required: false
        type: number
        default: 5
      delete_untagged:
        required: false
        type: boolean
        default: true

jobs:
  delete_versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old container versions
        uses: actions/delete-package-versions@v4.1.1
        with:
          delete-only-untagged-versions: ${{ inputs.delete_untagged || true }}
          min-versions-to-keep: ${{ inputs.min_versions_to_keep || 5 }}
          package-name: ${{ inputs.package_name || 'codechips/vastai-sdnext' }}
          package-type: ${{ inputs.package_type || 'container' }}
          token: ${{ secrets.GITHUB_TOKEN }}