name: Cleanup Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM UTC
  workflow_run:
    workflows: ["Docker Publish"]
    types:
      - completed

jobs:
  cleanup-main:
    name: Cleanup main SD.Next image
    uses: ./.github/workflows/delete-package-versions.yml
    with:
      package_name: 'vastai-sdnext'
      package_type: 'container'
      min_versions_to_keep: 5  # Keep last 5 versions
    permissions:
      packages: write
    secrets: inherit

  cleanup-untagged:
    name: Cleanup untagged versions
    uses: ./.github/workflows/delete-package-versions.yml
    with:
      package_name: 'vastai-sdnext'
      package_type: 'container'
      min_versions_to_keep: 2  # Keep fewer untagged versions
      delete_untagged_only: true
    permissions:
      packages: write
    secrets: inherit